title: Hingtak
email: hingtak@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Official blog with Wire&Cable.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: hingtak

# Build settings
theme: minima
plugins:
  - jekyll-feed